/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// user-defined fixed configurations
    /// </summary>
    [DataContract]
    public partial class ModelFlowChartExtensionFixedConfig : IEquatable<ModelFlowChartExtensionFixedConfig>
    { 
        /// <summary>
        /// list of model flow charts it is compatible with
        /// </summary>
        /// <value>list of model flow charts it is compatible with</value>
        [DataMember(Name="compatibility")]
        public List<string> Compatibility { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelFlowChartExtensionFixedConfig {\n");
            sb.Append("  Compatibility: ").Append(Compatibility).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ModelFlowChartExtensionFixedConfig)obj);
        }

        /// <summary>
        /// Returns true if ModelFlowChartExtensionFixedConfig instances are equal
        /// </summary>
        /// <param name="other">Instance of ModelFlowChartExtensionFixedConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelFlowChartExtensionFixedConfig other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Compatibility == other.Compatibility ||
                    Compatibility != null &&
                    Compatibility.SequenceEqual(other.Compatibility)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Compatibility != null)
                    hashCode = hashCode * 59 + Compatibility.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ModelFlowChartExtensionFixedConfig left, ModelFlowChartExtensionFixedConfig right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ModelFlowChartExtensionFixedConfig left, ModelFlowChartExtensionFixedConfig right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
