/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ModelFlowChartNode : IEquatable<ModelFlowChartNode>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// user-defined fixed config
        /// </summary>
        /// <value>user-defined fixed config</value>
        [DataMember(Name="fixed_config")]
        public Object FixedConfig { get; set; }

        /// <summary>
        /// all incoming and outgoing edges
        /// </summary>
        /// <value>all incoming and outgoing edges</value>
        [DataMember(Name="linked_edges")]
        public List<ModelFlowChartNodeLinkedEdges> LinkedEdges { get; set; }

        /// <summary>
        /// the id of the corresponding node components
        /// </summary>
        /// <value>the id of the corresponding node components</value>
        [DataMember(Name="contained_components_id")]
        public string ContainedComponentsId { get; set; }

        /// <summary>
        /// location in DB for retrieval of this node&#x27;s scripts
        /// </summary>
        /// <value>location in DB for retrieval of this node&#x27;s scripts</value>
        [DataMember(Name="scripts")]
        public string Scripts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelFlowChartNode {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FixedConfig: ").Append(FixedConfig).Append("\n");
            sb.Append("  LinkedEdges: ").Append(LinkedEdges).Append("\n");
            sb.Append("  ContainedComponentsId: ").Append(ContainedComponentsId).Append("\n");
            sb.Append("  Scripts: ").Append(Scripts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ModelFlowChartNode)obj);
        }

        /// <summary>
        /// Returns true if ModelFlowChartNode instances are equal
        /// </summary>
        /// <param name="other">Instance of ModelFlowChartNode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelFlowChartNode other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    FixedConfig == other.FixedConfig ||
                    FixedConfig != null &&
                    FixedConfig.Equals(other.FixedConfig)
                ) && 
                (
                    LinkedEdges == other.LinkedEdges ||
                    LinkedEdges != null &&
                    LinkedEdges.SequenceEqual(other.LinkedEdges)
                ) && 
                (
                    ContainedComponentsId == other.ContainedComponentsId ||
                    ContainedComponentsId != null &&
                    ContainedComponentsId.Equals(other.ContainedComponentsId)
                ) && 
                (
                    Scripts == other.Scripts ||
                    Scripts != null &&
                    Scripts.Equals(other.Scripts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (FixedConfig != null)
                    hashCode = hashCode * 59 + FixedConfig.GetHashCode();
                    if (LinkedEdges != null)
                    hashCode = hashCode * 59 + LinkedEdges.GetHashCode();
                    if (ContainedComponentsId != null)
                    hashCode = hashCode * 59 + ContainedComponentsId.GetHashCode();
                    if (Scripts != null)
                    hashCode = hashCode * 59 + Scripts.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ModelFlowChartNode left, ModelFlowChartNode right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ModelFlowChartNode left, ModelFlowChartNode right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
