# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ModelFlowChartMeta(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, kind: str=None, created_time: float=None, last_modified_time: float=None, author: str=None, edit_mode: str=None, config: object=None, comments: str=None):  # noqa: E501
        """ModelFlowChartMeta - a model defined in Swagger

        :param id: The id of this ModelFlowChartMeta.  # noqa: E501
        :type id: str
        :param kind: The kind of this ModelFlowChartMeta.  # noqa: E501
        :type kind: str
        :param created_time: The created_time of this ModelFlowChartMeta.  # noqa: E501
        :type created_time: float
        :param last_modified_time: The last_modified_time of this ModelFlowChartMeta.  # noqa: E501
        :type last_modified_time: float
        :param author: The author of this ModelFlowChartMeta.  # noqa: E501
        :type author: str
        :param edit_mode: The edit_mode of this ModelFlowChartMeta.  # noqa: E501
        :type edit_mode: str
        :param config: The config of this ModelFlowChartMeta.  # noqa: E501
        :type config: object
        :param comments: The comments of this ModelFlowChartMeta.  # noqa: E501
        :type comments: str
        """
        self.swagger_types = {
            'id': str,
            'kind': str,
            'created_time': float,
            'last_modified_time': float,
            'author': str,
            'edit_mode': str,
            'config': object,
            'comments': str
        }

        self.attribute_map = {
            'id': 'id',
            'kind': 'kind',
            'created_time': 'createdTime',
            'last_modified_time': 'lastModifiedTime',
            'author': 'author',
            'edit_mode': 'editMode',
            'config': 'config',
            'comments': 'comments'
        }
        self._id = id
        self._kind = kind
        self._created_time = created_time
        self._last_modified_time = last_modified_time
        self._author = author
        self._edit_mode = edit_mode
        self._config = config
        self._comments = comments

    @classmethod
    def from_dict(cls, dikt) -> 'ModelFlowChartMeta':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The modelFlowChartMeta of this ModelFlowChartMeta.  # noqa: E501
        :rtype: ModelFlowChartMeta
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ModelFlowChartMeta.


        :return: The id of this ModelFlowChartMeta.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ModelFlowChartMeta.


        :param id: The id of this ModelFlowChartMeta.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def kind(self) -> str:
        """Gets the kind of this ModelFlowChartMeta.


        :return: The kind of this ModelFlowChartMeta.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """Sets the kind of this ModelFlowChartMeta.


        :param kind: The kind of this ModelFlowChartMeta.
        :type kind: str
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def created_time(self) -> float:
        """Gets the created_time of this ModelFlowChartMeta.


        :return: The created_time of this ModelFlowChartMeta.
        :rtype: float
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time: float):
        """Sets the created_time of this ModelFlowChartMeta.


        :param created_time: The created_time of this ModelFlowChartMeta.
        :type created_time: float
        """

        self._created_time = created_time

    @property
    def last_modified_time(self) -> float:
        """Gets the last_modified_time of this ModelFlowChartMeta.


        :return: The last_modified_time of this ModelFlowChartMeta.
        :rtype: float
        """
        return self._last_modified_time

    @last_modified_time.setter
    def last_modified_time(self, last_modified_time: float):
        """Sets the last_modified_time of this ModelFlowChartMeta.


        :param last_modified_time: The last_modified_time of this ModelFlowChartMeta.
        :type last_modified_time: float
        """

        self._last_modified_time = last_modified_time

    @property
    def author(self) -> str:
        """Gets the author of this ModelFlowChartMeta.


        :return: The author of this ModelFlowChartMeta.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this ModelFlowChartMeta.


        :param author: The author of this ModelFlowChartMeta.
        :type author: str
        """

        self._author = author

    @property
    def edit_mode(self) -> str:
        """Gets the edit_mode of this ModelFlowChartMeta.


        :return: The edit_mode of this ModelFlowChartMeta.
        :rtype: str
        """
        return self._edit_mode

    @edit_mode.setter
    def edit_mode(self, edit_mode: str):
        """Sets the edit_mode of this ModelFlowChartMeta.


        :param edit_mode: The edit_mode of this ModelFlowChartMeta.
        :type edit_mode: str
        """

        self._edit_mode = edit_mode

    @property
    def config(self) -> object:
        """Gets the config of this ModelFlowChartMeta.


        :return: The config of this ModelFlowChartMeta.
        :rtype: object
        """
        return self._config

    @config.setter
    def config(self, config: object):
        """Sets the config of this ModelFlowChartMeta.


        :param config: The config of this ModelFlowChartMeta.
        :type config: object
        """

        self._config = config

    @property
    def comments(self) -> str:
        """Gets the comments of this ModelFlowChartMeta.


        :return: The comments of this ModelFlowChartMeta.
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments: str):
        """Sets the comments of this ModelFlowChartMeta.


        :param comments: The comments of this ModelFlowChartMeta.
        :type comments: str
        """

        self._comments = comments
