/*
 * Machine fault diagnosis
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ModelFlowChart;
import io.swagger.client.model.ModelFlowChartMeta;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ModelFlowChartApi
 */
@Ignore
public class ModelFlowChartApiTest {

    private final ModelFlowChartApi api = new ModelFlowChartApi();

    /**
     * delete a model flow chart
     *
     * delete a model flow chart
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelFlowModelFlowIdDeleteTest() throws ApiException {
        String modelFlowId = null;
        Object response = api.modelFlowModelFlowIdDelete(modelFlowId);

        // TODO: test validations
    }
    /**
     * retrieve a model flow chart
     *
     * retrieve a model flow chart
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelFlowModelFlowIdGetTest() throws ApiException {
        String modelFlowId = null;
        List<ModelFlowChartMeta> response = api.modelFlowModelFlowIdGet(modelFlowId);

        // TODO: test validations
    }
    /**
     * create a model flow chart
     *
     * create a model flow chart
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelFlowModelFlowIdPostTest() throws ApiException {
        String modelFlowId = null;
        ModelFlowChart modelFlowChart = null;
        Object response = api.modelFlowModelFlowIdPost(modelFlowId, modelFlowChart);

        // TODO: test validations
    }
    /**
     * update a model flow chart
     *
     * update a model flow chart
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void modelFlowModelFlowIdPutTest() throws ApiException {
        String modelFlowId = null;
        ModelFlowChart modelFlowChart = null;
        Object response = api.modelFlowModelFlowIdPut(modelFlowId, modelFlowChart);

        // TODO: test validations
    }
}
