/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ModelFlowChartExtension
    /// </summary>
    [DataContract]
        public partial class ModelFlowChartExtension :  IEquatable<ModelFlowChartExtension>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelFlowChartExtension" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="fixedConfig">fixedConfig.</param>
        /// <param name="installScript">the address in DB where the installation script is stored.</param>
        /// <param name="startScript">where to retrieve the extension starting script.</param>
        public ModelFlowChartExtension(string id = default(string), ModelFlowChartExtensionFixedConfig fixedConfig = default(ModelFlowChartExtensionFixedConfig), string installScript = default(string), string startScript = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for ModelFlowChartExtension and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            this.FixedConfig = fixedConfig;
            this.InstallScript = installScript;
            this.StartScript = startScript;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets FixedConfig
        /// </summary>
        [DataMember(Name="fixed_config", EmitDefaultValue=false)]
        public ModelFlowChartExtensionFixedConfig FixedConfig { get; set; }

        /// <summary>
        /// the address in DB where the installation script is stored
        /// </summary>
        /// <value>the address in DB where the installation script is stored</value>
        [DataMember(Name="install_script", EmitDefaultValue=false)]
        public string InstallScript { get; set; }

        /// <summary>
        /// where to retrieve the extension starting script
        /// </summary>
        /// <value>where to retrieve the extension starting script</value>
        [DataMember(Name="start_script", EmitDefaultValue=false)]
        public string StartScript { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelFlowChartExtension {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FixedConfig: ").Append(FixedConfig).Append("\n");
            sb.Append("  InstallScript: ").Append(InstallScript).Append("\n");
            sb.Append("  StartScript: ").Append(StartScript).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelFlowChartExtension);
        }

        /// <summary>
        /// Returns true if ModelFlowChartExtension instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelFlowChartExtension to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelFlowChartExtension input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.FixedConfig == input.FixedConfig ||
                    (this.FixedConfig != null &&
                    this.FixedConfig.Equals(input.FixedConfig))
                ) && 
                (
                    this.InstallScript == input.InstallScript ||
                    (this.InstallScript != null &&
                    this.InstallScript.Equals(input.InstallScript))
                ) && 
                (
                    this.StartScript == input.StartScript ||
                    (this.StartScript != null &&
                    this.StartScript.Equals(input.StartScript))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.FixedConfig != null)
                    hashCode = hashCode * 59 + this.FixedConfig.GetHashCode();
                if (this.InstallScript != null)
                    hashCode = hashCode * 59 + this.InstallScript.GetHashCode();
                if (this.StartScript != null)
                    hashCode = hashCode * 59 + this.StartScript.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
