sudo: required
branches:
  only:
  - master
dist: xenial
cache:
  directories:
  - "$HOME/.cache/pip"
matrix:
  include:
  - language: python
    name: Python 3.6 on Xenial
    python: 3.6
    env: TEST_SUITE=Xenial_Py36
  # - language: shell
  #   python: 3.6
  #   name: Python 3.6 on MacOS
  #   os: osx
  #   osx_image: xcode11.3
  #   env: TEST_SUITE=Mac_Py36
  - language: python
    name: Python 3.8 on Xenial
    python: 3.8
    env: TEST_SUITE=Xenial_Py36
  # - language: shell
  #   python: 3.8
  #   name: Python 3.8 on MacOS
  #   os: osx
  #   osx_image: xcode11.3
  #   env: TEST_SUITE=Mac_Py36
  # allow_failures:
  # - language: python
  #   python: 3.6
  #   name: Python 3.6 on MacOS
  #   os: osx
  #   osx_image: xcode11.3
  #   env: TEST_SUITE=Mac_Py36
  # - language: python
  #   python: 3.8
  #   name: Python 3.8 on MacOS
  #   os: osx
  #   osx_image: xcode11.3
  #   env: TEST_SUITE=Mac_Py36
  # fast_finish: true
install:
- echo "deb https://dl.bintray.com/sobolevn/deb git-secret main" | sudo tee -a /etc/apt/sources.list
- wget -qO - https://api.bintray.com/users/sobolevn/keys/gpg/public.key | sudo apt-key add -
- sudo apt-get update && sudo apt-get install git-secret
- pip install -r requirements.txt
before_script: 
- echo $GPG_PRIVATE_KEY | tr ',' '\n' > private_key.gpg
- gpg --import private_key.gpg
- git secret reveal
script:
- pytest --cov-config=.coveragerc --cov=backend
- python backend/servers/server.py
after_success:
- codecov
- coveralls
notifications:
  slack:
    secure: Eli1Ki7/+9S/bgYrFPHyxpqjl+s/uLoJ89mExslkMPzITPfa49542ay07n+m/aaWaCJAEsddx6bzeeWGLRAFiw8lJtaKYXI9Pt4FC9F3jxQLTbBHC4m/OnfnkKah8HEUWBVPdPbcXvNQGNiXKOE+rCfmM7vRc1mtEpbq37Vrmz3PljyihkADMi/MMYZSGiPgjADWi3Hym6jwQ7dVZEV3aTmvmvhXqHePfjwvafNZk86/higSvuLU6607+lsDQa7e4VQayCBXPGGNf+GALv3kfuc31zwP82Ku6UDZRWRgKPSiFbqS2Pdrvn9J9CiNexKNxS3WQ5L+R5fmbLJGnqvHPTO8EjRiqagRgEeUGm1gQdJ12QLjE++nFel/oisllnMsnIj8rqH6CzFPNsroZoatcH4eZHsyh4R+KrQfZuclMtzkwRsW1yu2qeT8TztQbB81hCRbzCCUp97mgqvpe+DfyLn37Xekv7ITsq6CMuXKoAkZUZVvRBqKhWYxChvSP6/4xwwWbgJHiC0TMqCeik0H7igva6L/TnOuKSE8X3y8/xe2CgJLW4wEU5ELZ9I1NLo5CsuqT45FbXKxEklQFXDGOBSYnTnDZyTsZUXM34LPaV7AUn+l3b2SReJ6w4WtBABniLvnh8+3wmN4l8tm8qrG1CMHgb75Vi4Ag36SYNHfuQ0=
  email: false
