/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelFlowChartValidationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ModelFlowChartValidationApiTests
    {
        private ModelFlowChartValidationApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ModelFlowChartValidationApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelFlowChartValidationApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ModelFlowChartValidationApi
            //Assert.IsInstanceOfType(typeof(ModelFlowChartValidationApi), instance, "instance is a ModelFlowChartValidationApi");
        }

        /// <summary>
        /// Test ModelFlowValidationKindIdPost
        /// </summary>
        [Test]
        public void ModelFlowValidationKindIdPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string kind = null;
            //string id = null;
            //var response = instance.ModelFlowValidationKindIdPost(kind, id);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
    }

}
