/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelFlowChartGraph
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelFlowChartGraphTests
    {
        // TODO uncomment below to declare an instance variable for ModelFlowChartGraph
        //private ModelFlowChartGraph instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelFlowChartGraph
            //instance = new ModelFlowChartGraph();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelFlowChartGraph
        /// </summary>
        [Test]
        public void ModelFlowChartGraphInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelFlowChartGraph
            //Assert.IsInstanceOfType<ModelFlowChartGraph> (instance, "variable 'instance' is a ModelFlowChartGraph");
        }


        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Test]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }
        /// <summary>
        /// Test the property 'NodeComponents'
        /// </summary>
        [Test]
        public void NodeComponentsTest()
        {
            // TODO unit test for the property 'NodeComponents'
        }
        /// <summary>
        /// Test the property 'Edges'
        /// </summary>
        [Test]
        public void EdgesTest()
        {
            // TODO unit test for the property 'Edges'
        }
        /// <summary>
        /// Test the property 'Extensions'
        /// </summary>
        [Test]
        public void ExtensionsTest()
        {
            // TODO unit test for the property 'Extensions'
        }

    }

}
