/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelFlowChartNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelFlowChartNodeTests
    {
        // TODO uncomment below to declare an instance variable for ModelFlowChartNode
        //private ModelFlowChartNode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelFlowChartNode
            //instance = new ModelFlowChartNode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelFlowChartNode
        /// </summary>
        [Test]
        public void ModelFlowChartNodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelFlowChartNode
            //Assert.IsInstanceOfType<ModelFlowChartNode> (instance, "variable 'instance' is a ModelFlowChartNode");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FixedConfig'
        /// </summary>
        [Test]
        public void FixedConfigTest()
        {
            // TODO unit test for the property 'FixedConfig'
        }
        /// <summary>
        /// Test the property 'LinkedEdges'
        /// </summary>
        [Test]
        public void LinkedEdgesTest()
        {
            // TODO unit test for the property 'LinkedEdges'
        }
        /// <summary>
        /// Test the property 'ContainedComponentsId'
        /// </summary>
        [Test]
        public void ContainedComponentsIdTest()
        {
            // TODO unit test for the property 'ContainedComponentsId'
        }
        /// <summary>
        /// Test the property 'Scripts'
        /// </summary>
        [Test]
        public void ScriptsTest()
        {
            // TODO unit test for the property 'Scripts'
        }

    }

}
