/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelFlowChart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelFlowChartTests
    {
        // TODO uncomment below to declare an instance variable for ModelFlowChart
        //private ModelFlowChart instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelFlowChart
            //instance = new ModelFlowChart();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelFlowChart
        /// </summary>
        [Test]
        public void ModelFlowChartInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelFlowChart
            //Assert.IsInstanceOfType<ModelFlowChart> (instance, "variable 'instance' is a ModelFlowChart");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Graph'
        /// </summary>
        [Test]
        public void GraphTest()
        {
            // TODO unit test for the property 'Graph'
        }

    }

}
