/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelFlowChartExtension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelFlowChartExtensionTests
    {
        // TODO uncomment below to declare an instance variable for ModelFlowChartExtension
        //private ModelFlowChartExtension instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelFlowChartExtension
            //instance = new ModelFlowChartExtension();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelFlowChartExtension
        /// </summary>
        [Test]
        public void ModelFlowChartExtensionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelFlowChartExtension
            //Assert.IsInstanceOfType<ModelFlowChartExtension> (instance, "variable 'instance' is a ModelFlowChartExtension");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FixedConfig'
        /// </summary>
        [Test]
        public void FixedConfigTest()
        {
            // TODO unit test for the property 'FixedConfig'
        }
        /// <summary>
        /// Test the property 'InstallScript'
        /// </summary>
        [Test]
        public void InstallScriptTest()
        {
            // TODO unit test for the property 'InstallScript'
        }
        /// <summary>
        /// Test the property 'StartScript'
        /// </summary>
        [Test]
        public void StartScriptTest()
        {
            // TODO unit test for the property 'StartScript'
        }

    }

}
