/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ModelFlowChartExtensionApiController : ControllerBase
    { 
        /// <summary>
        /// delete a model flow chart extension
        /// </summary>
        /// <remarks>delete a model flow chart extension</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <response code="200">deleted a model flow chart extension</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">no model flow chart found</response>
        /// <response code="500">internal server error</response>
        [HttpDelete]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}/extension")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdExtensionDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "deleted a model flow chart extension")]
        public virtual IActionResult ModelFlowModelFlowIdExtensionDelete([FromRoute][Required]string modelFlowId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// retrieve a model flow chart extension
        /// </summary>
        /// <remarks>retrieve a model flow chart extension</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <response code="200">model flow chart returned</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">no model flow chart extension found</response>
        /// <response code="500">internal server error</response>
        [HttpGet]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}/extension")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdExtensionGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ModelFlowChartExtensionMeta>), description: "model flow chart returned")]
        public virtual IActionResult ModelFlowModelFlowIdExtensionGet([FromRoute][Required]string modelFlowId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ModelFlowChartExtensionMeta>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "[ {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n}, {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<ModelFlowChartExtensionMeta>>(exampleJson)
                        : default(List<ModelFlowChartExtensionMeta>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// create a model flow chart extension
        /// </summary>
        /// <remarks>create a model flow chart extension</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChartExtension">model flow chart extension</param>
        /// <response code="200">model flow chart extension successfully created</response>
        /// <response code="400">invalid model flow chart extension input</response>
        /// <response code="500">internal server error</response>
        [HttpPost]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}/extension")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdExtensionPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "model flow chart extension successfully created")]
        public virtual IActionResult ModelFlowModelFlowIdExtensionPost([FromRoute][Required]string modelFlowId, [FromQuery][Required()]ModelFlowChartExtensionMeta modelFlowChartExtension)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// update a model flow chart extension
        /// </summary>
        /// <remarks>update a model flow chart extension</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChartExtension">model flow chart extension</param>
        /// <response code="200">model flow chart successfully updated</response>
        /// <response code="400">invalid model flow chart extension input</response>
        /// <response code="500">internal server error</response>
        [HttpPut]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}/extension")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdExtensionPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "model flow chart successfully updated")]
        public virtual IActionResult ModelFlowModelFlowIdExtensionPut([FromRoute][Required]string modelFlowId, [FromQuery][Required()]ModelFlowChartExtensionMeta modelFlowChartExtension)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
