/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ModelFlowChartApiController : ControllerBase
    { 
        /// <summary>
        /// delete a model flow chart
        /// </summary>
        /// <remarks>delete a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <response code="200">deleted a model flow chart</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">no model flow chart satisfies the search criteria</response>
        /// <response code="500">internal server error</response>
        [HttpDelete]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "deleted a model flow chart")]
        public virtual IActionResult ModelFlowModelFlowIdDelete([FromRoute][Required]string modelFlowId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// retrieve a model flow chart
        /// </summary>
        /// <remarks>retrieve a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <response code="200">model flow chart returned</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">no model flow chart satisfies the search criteria</response>
        /// <response code="500">internal server error</response>
        [HttpGet]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ModelFlowChartMeta>), description: "model flow chart returned")]
        public virtual IActionResult ModelFlowModelFlowIdGet([FromRoute][Required]string modelFlowId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ModelFlowChartMeta>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "[ {\n  \"lastModifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"editMode\" : \"editMode\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\",\n  \"config\" : { }\n}, {\n  \"lastModifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"editMode\" : \"editMode\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\",\n  \"config\" : { }\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<ModelFlowChartMeta>>(exampleJson)
                        : default(List<ModelFlowChartMeta>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// create a model flow chart
        /// </summary>
        /// <remarks>create a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <response code="200">model flow chart successfully created</response>
        /// <response code="400">invalid model flow chart input</response>
        /// <response code="500">internal server error</response>
        [HttpPost]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "model flow chart successfully created")]
        public virtual IActionResult ModelFlowModelFlowIdPost([FromRoute][Required]string modelFlowId, [FromQuery][Required()]ModelFlowChart modelFlowChart)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// update a model flow chart
        /// </summary>
        /// <remarks>update a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <response code="200">model flow chart successfully created</response>
        /// <response code="400">invalid model flow chart input</response>
        /// <response code="500">internal server error</response>
        [HttpPut]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/{modelFlowId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowModelFlowIdPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "model flow chart successfully created")]
        public virtual IActionResult ModelFlowModelFlowIdPut([FromRoute][Required]string modelFlowId, [FromQuery][Required()]ModelFlowChart modelFlowChart)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
