/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ModelFlowChartNodeApiController : ControllerBase
    { 
        /// <summary>
        /// delete a node&#x27;s information in a model flow chart
        /// </summary>
        /// <remarks>delete a node&#x27;s information in a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="nodeId">node&#x27;s id in a model flow chart</param>
        /// <response code="200">node deleted</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">model flow chart node not found</response>
        /// <response code="500">internal server error</response>
        [HttpDelete]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/node/{modelFlowId}/{nodeId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowNodeModelFlowIdNodeIdDelete")]
        [SwaggerResponse(statusCode: 200, type: typeof(Object), description: "node deleted")]
        public virtual IActionResult ModelFlowNodeModelFlowIdNodeIdDelete([FromRoute][Required]string modelFlowId, [FromRoute][Required]string nodeId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Object));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{ }";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<Object>(exampleJson)
                        : default(Object);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// retrieve a node&#x27;s information in a model flow chart
        /// </summary>
        /// <remarks>retrieve a node&#x27;s information in a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="nodeId">node&#x27;s id in a model flow chart</param>
        /// <response code="200">node returned</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">model flow chart node not found</response>
        /// <response code="500">internal server error</response>
        [HttpGet]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/node/{modelFlowId}/{nodeId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowNodeModelFlowIdNodeIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ModelFlowChartNodeMeta>), description: "node returned")]
        public virtual IActionResult ModelFlowNodeModelFlowIdNodeIdGet([FromRoute][Required]string modelFlowId, [FromRoute][Required]string nodeId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ModelFlowChartNodeMeta>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "[ {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n}, {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<ModelFlowChartNodeMeta>>(exampleJson)
                        : default(List<ModelFlowChartNodeMeta>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// create a node&#x27;s information in a model flow chart
        /// </summary>
        /// <remarks>create a node&#x27;s information in a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="nodeId">node&#x27;s id in a model flow chart</param>
        /// <response code="200">node created</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">model flow chart not found. create one first.</response>
        /// <response code="500">internal server error</response>
        [HttpPost]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/node/{modelFlowId}/{nodeId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowNodeModelFlowIdNodeIdPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ModelFlowChartNodeMeta>), description: "node created")]
        public virtual IActionResult ModelFlowNodeModelFlowIdNodeIdPost([FromRoute][Required]string modelFlowId, [FromRoute][Required]string nodeId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ModelFlowChartNodeMeta>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "[ {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n}, {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<ModelFlowChartNodeMeta>>(exampleJson)
                        : default(List<ModelFlowChartNodeMeta>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// update a node&#x27;s information in a model flow chart
        /// </summary>
        /// <remarks>update a node&#x27;s information in a model flow chart</remarks>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="nodeId">node&#x27;s id in a model flow chart</param>
        /// <response code="200">node updated</response>
        /// <response code="400">input is invalid</response>
        /// <response code="404">model flow chart not found. create one first.</response>
        /// <response code="500">internal server error</response>
        [HttpPut]
        [Route("/zhuofusong/machine-fault-diagnosis/1.0.0/modelFlow/node/{modelFlowId}/{nodeId}")]
        [ValidateModelState]
        [SwaggerOperation("ModelFlowNodeModelFlowIdNodeIdPut")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ModelFlowChartNodeMeta>), description: "node updated")]
        public virtual IActionResult ModelFlowNodeModelFlowIdNodeIdPut([FromRoute][Required]string modelFlowId, [FromRoute][Required]string nodeId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<ModelFlowChartNodeMeta>));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "[ {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n}, {\n  \"modifiedTime\" : 6.027456183070403,\n  \"comments\" : \"comments\",\n  \"kind\" : \"kind\",\n  \"author\" : \"author\",\n  \"createdTime\" : 0.8008281904610115,\n  \"id\" : \"id\"\n} ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<ModelFlowChartNodeMeta>>(exampleJson)
                        : default(List<ModelFlowChartNodeMeta>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
