# coding: utf-8

"""
    Machine fault diagnosis

    List of top level server APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.model_flow_chart_edge_api import ModelFlowChartEdgeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelFlowChartEdgeApi(unittest.TestCase):
    """ModelFlowChartEdgeApi unit test stubs"""

    def setUp(self):
        self.api = api.model_flow_chart_edge_api.ModelFlowChartEdgeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_model_flow_node_model_flow_id_edge_id_delete(self):
        """Test case for model_flow_node_model_flow_id_edge_id_delete

        delete an edge's information in a model flow chart  # noqa: E501
        """
        pass

    def test_model_flow_node_model_flow_id_edge_id_get(self):
        """Test case for model_flow_node_model_flow_id_edge_id_get

        retrieve an edge's information in a model flow chart  # noqa: E501
        """
        pass

    def test_model_flow_node_model_flow_id_edge_id_post(self):
        """Test case for model_flow_node_model_flow_id_edge_id_post

        create an edge's information in a model flow chart  # noqa: E501
        """
        pass

    def test_model_flow_node_model_flow_id_edge_id_put(self):
        """Test case for model_flow_node_model_flow_id_edge_id_put

        update an edge's information in a model flow chart  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
