# coding: utf-8

"""
    Machine fault diagnosis

    List of top level server APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.model_flow_chart_node_component_meta import ModelFlowChartNodeComponentMeta  # noqa: E501
from swagger_client.rest import ApiException


class TestModelFlowChartNodeComponentMeta(unittest.TestCase):
    """ModelFlowChartNodeComponentMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelFlowChartNodeComponentMeta(self):
        """Test ModelFlowChartNodeComponentMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model_flow_chart_node_component_meta.ModelFlowChartNodeComponentMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
