# coding: utf-8

"""
    Machine fault diagnosis

    List of top level server APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.model_flow_chart_extension_api import ModelFlowChartExtensionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelFlowChartExtensionApi(unittest.TestCase):
    """ModelFlowChartExtensionApi unit test stubs"""

    def setUp(self):
        self.api = api.model_flow_chart_extension_api.ModelFlowChartExtensionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_model_flow_model_flow_id_extension_delete(self):
        """Test case for model_flow_model_flow_id_extension_delete

        delete a model flow chart extension  # noqa: E501
        """
        pass

    def test_model_flow_model_flow_id_extension_get(self):
        """Test case for model_flow_model_flow_id_extension_get

        retrieve a model flow chart extension  # noqa: E501
        """
        pass

    def test_model_flow_model_flow_id_extension_post(self):
        """Test case for model_flow_model_flow_id_extension_post

        create a model flow chart extension  # noqa: E501
        """
        pass

    def test_model_flow_model_flow_id_extension_put(self):
        """Test case for model_flow_model_flow_id_extension_put

        update a model flow chart extension  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
