/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelFlowChartEdgeMeta struct {

	Id string `json:"id"`
	// the kind of string based on which
	Kind string `json:"kind"`

	CreatedTime *BigDecimal `json:"createdTime,omitempty"`

	ModifiedTime *BigDecimal `json:"modifiedTime,omitempty"`

	Author string `json:"author,omitempty"`

	Comments string `json:"comments,omitempty"`
}
