/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelFlowChartNodeComponent struct {

	Id string `json:"id"`

	LinkedNodeId string `json:"linked_node_id,omitempty"`
	// user-defined fixed config
	FixedConfig *interface{} `json:"fixed_config,omitempty"`

	ComponentSubGraph *ModelFlowChart `json:"component_sub_graph,omitempty"`
}
