/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelFlowChartNode struct {

	Id string `json:"id"`
	// user-defined fixed config
	FixedConfig *interface{} `json:"fixed_config,omitempty"`
	// all incoming and outgoing edges
	LinkedEdges []ModelFlowChartNodeLinkedEdges `json:"linked_edges,omitempty"`
	// the id of the corresponding node components
	ContainedComponentsId string `json:"contained_components_id,omitempty"`
	// location in DB for retrieval of this node's scripts
	Scripts string `json:"scripts,omitempty"`
}
