/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// user-defined fixed configurations
type ModelFlowChartExtensionFixedConfig struct {
	// list of model flow charts it is compatible with
	Compatibility []string `json:"compatibility,omitempty"`
}
