/*
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModelFlowChartNodeLinkedEdges struct {

	Direction string `json:"direction,omitempty"`
	// variable mapping between two nodes
	EdgeDataFlow *interface{} `json:"edge_data_flow,omitempty"`
}
