/**
 * Machine fault diagnosis
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ModelFlowChartEdgeMeta { 
    id: string;
    /**
     * the kind of string based on which
     */
    kind: string;
    createdTime?: number;
    modifiedTime?: number;
    author?: string;
    comments?: string;
}