/**
 * Machine fault diagnosis
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelFlowChartExtensionFixedConfig } from './modelFlowChartExtensionFixedConfig';

export interface ModelFlowChartExtension { 
    id: string;
    fixedConfig?: ModelFlowChartExtensionFixedConfig;
    /**
     * the address in DB where the installation script is stored
     */
    installScript?: string;
    /**
     * where to retrieve the extension starting script
     */
    startScript?: string;
}