/**
 * Machine fault diagnosis
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ModelFlowChart } from '../model/modelFlowChart';
import { ModelFlowChartMeta } from '../model/modelFlowChartMeta';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ModelFlowChartService {

    protected basePath = 'https://virtserver.swaggerhub.com/zhuofusong/machine-fault-diagnosis/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * delete a model flow chart
     * delete a model flow chart
     * @param modelFlowId model flow chart id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowModelFlowIdDelete(modelFlowId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public modelFlowModelFlowIdDelete(modelFlowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public modelFlowModelFlowIdDelete(modelFlowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public modelFlowModelFlowIdDelete(modelFlowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowModelFlowIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/modelFlow/${encodeURIComponent(String(modelFlowId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * retrieve a model flow chart
     * retrieve a model flow chart
     * @param modelFlowId model flow chart id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowModelFlowIdGet(modelFlowId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ModelFlowChartMeta>>;
    public modelFlowModelFlowIdGet(modelFlowId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ModelFlowChartMeta>>>;
    public modelFlowModelFlowIdGet(modelFlowId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ModelFlowChartMeta>>>;
    public modelFlowModelFlowIdGet(modelFlowId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowModelFlowIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ModelFlowChartMeta>>('get',`${this.basePath}/modelFlow/${encodeURIComponent(String(modelFlowId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create a model flow chart
     * create a model flow chart
     * @param modelFlowId model flow chart id
     * @param modelFlowChart model flow chart
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowModelFlowIdPost(modelFlowId: string, modelFlowChart: ModelFlowChart, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public modelFlowModelFlowIdPost(modelFlowId: string, modelFlowChart: ModelFlowChart, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public modelFlowModelFlowIdPost(modelFlowId: string, modelFlowChart: ModelFlowChart, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public modelFlowModelFlowIdPost(modelFlowId: string, modelFlowChart: ModelFlowChart, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowModelFlowIdPost.');
        }

        if (modelFlowChart === null || modelFlowChart === undefined) {
            throw new Error('Required parameter modelFlowChart was null or undefined when calling modelFlowModelFlowIdPost.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (modelFlowChart !== undefined && modelFlowChart !== null) {
            queryParameters = queryParameters.set('modelFlowChart', <any>modelFlowChart);
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/modelFlow/${encodeURIComponent(String(modelFlowId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update a model flow chart
     * update a model flow chart
     * @param modelFlowId model flow chart id
     * @param modelFlowChart model flow chart
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowModelFlowIdPut(modelFlowId: string, modelFlowChart: ModelFlowChart, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public modelFlowModelFlowIdPut(modelFlowId: string, modelFlowChart: ModelFlowChart, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public modelFlowModelFlowIdPut(modelFlowId: string, modelFlowChart: ModelFlowChart, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public modelFlowModelFlowIdPut(modelFlowId: string, modelFlowChart: ModelFlowChart, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowModelFlowIdPut.');
        }

        if (modelFlowChart === null || modelFlowChart === undefined) {
            throw new Error('Required parameter modelFlowChart was null or undefined when calling modelFlowModelFlowIdPut.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (modelFlowChart !== undefined && modelFlowChart !== null) {
            queryParameters = queryParameters.set('modelFlowChart', <any>modelFlowChart);
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/modelFlow/${encodeURIComponent(String(modelFlowId))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
