/**
 * Machine fault diagnosis
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ModelFlowChartNodeMeta } from '../model/modelFlowChartNodeMeta';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ModelFlowChartNodeService {

    protected basePath = 'https://virtserver.swaggerhub.com/zhuofusong/machine-fault-diagnosis/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * delete a node&#x27;s information in a model flow chart
     * delete a node&#x27;s information in a model flow chart
     * @param modelFlowId model flow chart id
     * @param nodeId node&#x27;s id in a model flow chart
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowNodeModelFlowIdNodeIdDelete(modelFlowId: string, nodeId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public modelFlowNodeModelFlowIdNodeIdDelete(modelFlowId: string, nodeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public modelFlowNodeModelFlowIdNodeIdDelete(modelFlowId: string, nodeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public modelFlowNodeModelFlowIdNodeIdDelete(modelFlowId: string, nodeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdDelete.');
        }

        if (nodeId === null || nodeId === undefined) {
            throw new Error('Required parameter nodeId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/modelFlow/node/${encodeURIComponent(String(modelFlowId))}/${encodeURIComponent(String(nodeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * retrieve a node&#x27;s information in a model flow chart
     * retrieve a node&#x27;s information in a model flow chart
     * @param modelFlowId model flow chart id
     * @param nodeId node&#x27;s id in a model flow chart
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowNodeModelFlowIdNodeIdGet(modelFlowId: string, nodeId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ModelFlowChartNodeMeta>>;
    public modelFlowNodeModelFlowIdNodeIdGet(modelFlowId: string, nodeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ModelFlowChartNodeMeta>>>;
    public modelFlowNodeModelFlowIdNodeIdGet(modelFlowId: string, nodeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ModelFlowChartNodeMeta>>>;
    public modelFlowNodeModelFlowIdNodeIdGet(modelFlowId: string, nodeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdGet.');
        }

        if (nodeId === null || nodeId === undefined) {
            throw new Error('Required parameter nodeId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ModelFlowChartNodeMeta>>('get',`${this.basePath}/modelFlow/node/${encodeURIComponent(String(modelFlowId))}/${encodeURIComponent(String(nodeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create a node&#x27;s information in a model flow chart
     * create a node&#x27;s information in a model flow chart
     * @param modelFlowId model flow chart id
     * @param nodeId node&#x27;s id in a model flow chart
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowNodeModelFlowIdNodeIdPost(modelFlowId: string, nodeId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ModelFlowChartNodeMeta>>;
    public modelFlowNodeModelFlowIdNodeIdPost(modelFlowId: string, nodeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ModelFlowChartNodeMeta>>>;
    public modelFlowNodeModelFlowIdNodeIdPost(modelFlowId: string, nodeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ModelFlowChartNodeMeta>>>;
    public modelFlowNodeModelFlowIdNodeIdPost(modelFlowId: string, nodeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdPost.');
        }

        if (nodeId === null || nodeId === undefined) {
            throw new Error('Required parameter nodeId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdPost.');
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ModelFlowChartNodeMeta>>('post',`${this.basePath}/modelFlow/node/${encodeURIComponent(String(modelFlowId))}/${encodeURIComponent(String(nodeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update a node&#x27;s information in a model flow chart
     * update a node&#x27;s information in a model flow chart
     * @param modelFlowId model flow chart id
     * @param nodeId node&#x27;s id in a model flow chart
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public modelFlowNodeModelFlowIdNodeIdPut(modelFlowId: string, nodeId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<ModelFlowChartNodeMeta>>;
    public modelFlowNodeModelFlowIdNodeIdPut(modelFlowId: string, nodeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ModelFlowChartNodeMeta>>>;
    public modelFlowNodeModelFlowIdNodeIdPut(modelFlowId: string, nodeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ModelFlowChartNodeMeta>>>;
    public modelFlowNodeModelFlowIdNodeIdPut(modelFlowId: string, nodeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (modelFlowId === null || modelFlowId === undefined) {
            throw new Error('Required parameter modelFlowId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdPut.');
        }

        if (nodeId === null || nodeId === undefined) {
            throw new Error('Required parameter nodeId was null or undefined when calling modelFlowNodeModelFlowIdNodeIdPut.');
        }

        let headers = this.defaultHeaders;

        // authentication (application) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ModelFlowChartNodeMeta>>('put',`${this.basePath}/modelFlow/node/${encodeURIComponent(String(modelFlowId))}/${encodeURIComponent(String(nodeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
