/* 
 * Machine fault diagnosis
 *
 * List of top level server APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IModelFlowChartApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// delete a model flow chart
        /// </summary>
        /// <remarks>
        /// delete a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Object</returns>
        Object ModelFlowModelFlowIdDelete (string modelFlowId);

        /// <summary>
        /// delete a model flow chart
        /// </summary>
        /// <remarks>
        /// delete a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ModelFlowModelFlowIdDeleteWithHttpInfo (string modelFlowId);
        /// <summary>
        /// retrieve a model flow chart
        /// </summary>
        /// <remarks>
        /// retrieve a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>List&lt;ModelFlowChartMeta&gt;</returns>
        List<ModelFlowChartMeta> ModelFlowModelFlowIdGet (string modelFlowId);

        /// <summary>
        /// retrieve a model flow chart
        /// </summary>
        /// <remarks>
        /// retrieve a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>ApiResponse of List&lt;ModelFlowChartMeta&gt;</returns>
        ApiResponse<List<ModelFlowChartMeta>> ModelFlowModelFlowIdGetWithHttpInfo (string modelFlowId);
        /// <summary>
        /// create a model flow chart
        /// </summary>
        /// <remarks>
        /// create a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Object</returns>
        Object ModelFlowModelFlowIdPost (string modelFlowId, ModelFlowChart modelFlowChart);

        /// <summary>
        /// create a model flow chart
        /// </summary>
        /// <remarks>
        /// create a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ModelFlowModelFlowIdPostWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart);
        /// <summary>
        /// update a model flow chart
        /// </summary>
        /// <remarks>
        /// update a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Object</returns>
        Object ModelFlowModelFlowIdPut (string modelFlowId, ModelFlowChart modelFlowChart);

        /// <summary>
        /// update a model flow chart
        /// </summary>
        /// <remarks>
        /// update a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> ModelFlowModelFlowIdPutWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// delete a model flow chart
        /// </summary>
        /// <remarks>
        /// delete a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ModelFlowModelFlowIdDeleteAsync (string modelFlowId);

        /// <summary>
        /// delete a model flow chart
        /// </summary>
        /// <remarks>
        /// delete a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ModelFlowModelFlowIdDeleteAsyncWithHttpInfo (string modelFlowId);
        /// <summary>
        /// retrieve a model flow chart
        /// </summary>
        /// <remarks>
        /// retrieve a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of List&lt;ModelFlowChartMeta&gt;</returns>
        System.Threading.Tasks.Task<List<ModelFlowChartMeta>> ModelFlowModelFlowIdGetAsync (string modelFlowId);

        /// <summary>
        /// retrieve a model flow chart
        /// </summary>
        /// <remarks>
        /// retrieve a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of ApiResponse (List&lt;ModelFlowChartMeta&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ModelFlowChartMeta>>> ModelFlowModelFlowIdGetAsyncWithHttpInfo (string modelFlowId);
        /// <summary>
        /// create a model flow chart
        /// </summary>
        /// <remarks>
        /// create a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ModelFlowModelFlowIdPostAsync (string modelFlowId, ModelFlowChart modelFlowChart);

        /// <summary>
        /// create a model flow chart
        /// </summary>
        /// <remarks>
        /// create a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ModelFlowModelFlowIdPostAsyncWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart);
        /// <summary>
        /// update a model flow chart
        /// </summary>
        /// <remarks>
        /// update a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> ModelFlowModelFlowIdPutAsync (string modelFlowId, ModelFlowChart modelFlowChart);

        /// <summary>
        /// update a model flow chart
        /// </summary>
        /// <remarks>
        /// update a model flow chart
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ModelFlowModelFlowIdPutAsyncWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ModelFlowChartApi : IModelFlowChartApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelFlowChartApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ModelFlowChartApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelFlowChartApi"/> class
        /// </summary>
        /// <returns></returns>
        public ModelFlowChartApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelFlowChartApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ModelFlowChartApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// delete a model flow chart delete a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Object</returns>
        public Object ModelFlowModelFlowIdDelete (string modelFlowId)
        {
             ApiResponse<Object> localVarResponse = ModelFlowModelFlowIdDeleteWithHttpInfo(modelFlowId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// delete a model flow chart delete a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ModelFlowModelFlowIdDeleteWithHttpInfo (string modelFlowId)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdDelete");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// delete a model flow chart delete a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ModelFlowModelFlowIdDeleteAsync (string modelFlowId)
        {
             ApiResponse<Object> localVarResponse = await ModelFlowModelFlowIdDeleteAsyncWithHttpInfo(modelFlowId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// delete a model flow chart delete a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ModelFlowModelFlowIdDeleteAsyncWithHttpInfo (string modelFlowId)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdDelete");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// retrieve a model flow chart retrieve a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>List&lt;ModelFlowChartMeta&gt;</returns>
        public List<ModelFlowChartMeta> ModelFlowModelFlowIdGet (string modelFlowId)
        {
             ApiResponse<List<ModelFlowChartMeta>> localVarResponse = ModelFlowModelFlowIdGetWithHttpInfo(modelFlowId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// retrieve a model flow chart retrieve a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>ApiResponse of List&lt;ModelFlowChartMeta&gt;</returns>
        public ApiResponse< List<ModelFlowChartMeta> > ModelFlowModelFlowIdGetWithHttpInfo (string modelFlowId)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdGet");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ModelFlowChartMeta>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ModelFlowChartMeta>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ModelFlowChartMeta>)));
        }

        /// <summary>
        /// retrieve a model flow chart retrieve a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of List&lt;ModelFlowChartMeta&gt;</returns>
        public async System.Threading.Tasks.Task<List<ModelFlowChartMeta>> ModelFlowModelFlowIdGetAsync (string modelFlowId)
        {
             ApiResponse<List<ModelFlowChartMeta>> localVarResponse = await ModelFlowModelFlowIdGetAsyncWithHttpInfo(modelFlowId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// retrieve a model flow chart retrieve a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <returns>Task of ApiResponse (List&lt;ModelFlowChartMeta&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ModelFlowChartMeta>>> ModelFlowModelFlowIdGetAsyncWithHttpInfo (string modelFlowId)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdGet");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ModelFlowChartMeta>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ModelFlowChartMeta>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ModelFlowChartMeta>)));
        }

        /// <summary>
        /// create a model flow chart create a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Object</returns>
        public Object ModelFlowModelFlowIdPost (string modelFlowId, ModelFlowChart modelFlowChart)
        {
             ApiResponse<Object> localVarResponse = ModelFlowModelFlowIdPostWithHttpInfo(modelFlowId, modelFlowChart);
             return localVarResponse.Data;
        }

        /// <summary>
        /// create a model flow chart create a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ModelFlowModelFlowIdPostWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdPost");
            // verify the required parameter 'modelFlowChart' is set
            if (modelFlowChart == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowChart' when calling ModelFlowChartApi->ModelFlowModelFlowIdPost");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            if (modelFlowChart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "modelFlowChart", modelFlowChart)); // query parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// create a model flow chart create a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ModelFlowModelFlowIdPostAsync (string modelFlowId, ModelFlowChart modelFlowChart)
        {
             ApiResponse<Object> localVarResponse = await ModelFlowModelFlowIdPostAsyncWithHttpInfo(modelFlowId, modelFlowChart);
             return localVarResponse.Data;

        }

        /// <summary>
        /// create a model flow chart create a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ModelFlowModelFlowIdPostAsyncWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdPost");
            // verify the required parameter 'modelFlowChart' is set
            if (modelFlowChart == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowChart' when calling ModelFlowChartApi->ModelFlowModelFlowIdPost");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            if (modelFlowChart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "modelFlowChart", modelFlowChart)); // query parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// update a model flow chart update a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Object</returns>
        public Object ModelFlowModelFlowIdPut (string modelFlowId, ModelFlowChart modelFlowChart)
        {
             ApiResponse<Object> localVarResponse = ModelFlowModelFlowIdPutWithHttpInfo(modelFlowId, modelFlowChart);
             return localVarResponse.Data;
        }

        /// <summary>
        /// update a model flow chart update a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > ModelFlowModelFlowIdPutWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdPut");
            // verify the required parameter 'modelFlowChart' is set
            if (modelFlowChart == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowChart' when calling ModelFlowChartApi->ModelFlowModelFlowIdPut");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            if (modelFlowChart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "modelFlowChart", modelFlowChart)); // query parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// update a model flow chart update a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> ModelFlowModelFlowIdPutAsync (string modelFlowId, ModelFlowChart modelFlowChart)
        {
             ApiResponse<Object> localVarResponse = await ModelFlowModelFlowIdPutAsyncWithHttpInfo(modelFlowId, modelFlowChart);
             return localVarResponse.Data;

        }

        /// <summary>
        /// update a model flow chart update a model flow chart
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="modelFlowId">model flow chart id</param>
        /// <param name="modelFlowChart">model flow chart</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ModelFlowModelFlowIdPutAsyncWithHttpInfo (string modelFlowId, ModelFlowChart modelFlowChart)
        {
            // verify the required parameter 'modelFlowId' is set
            if (modelFlowId == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowId' when calling ModelFlowChartApi->ModelFlowModelFlowIdPut");
            // verify the required parameter 'modelFlowChart' is set
            if (modelFlowChart == null)
                throw new ApiException(400, "Missing required parameter 'modelFlowChart' when calling ModelFlowChartApi->ModelFlowModelFlowIdPut");

            var localVarPath = "/modelFlow/{modelFlowId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (modelFlowId != null) localVarPathParams.Add("modelFlowId", this.Configuration.ApiClient.ParameterToString(modelFlowId)); // path parameter
            if (modelFlowChart != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "modelFlowChart", modelFlowChart)); // query parameter
            // authentication (application) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ModelFlowModelFlowIdPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

    }
}
