# coding: utf-8

"""
    Machine fault diagnosis

    List of top level server APIs  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ModelFlowChartExtensionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def model_flow_model_flow_id_extension_delete(self, model_flow_id, **kwargs):  # noqa: E501
        """delete a model flow chart extension  # noqa: E501

        delete a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_delete(model_flow_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.model_flow_model_flow_id_extension_delete_with_http_info(model_flow_id, **kwargs)  # noqa: E501
        else:
            (data) = self.model_flow_model_flow_id_extension_delete_with_http_info(model_flow_id, **kwargs)  # noqa: E501
            return data

    def model_flow_model_flow_id_extension_delete_with_http_info(self, model_flow_id, **kwargs):  # noqa: E501
        """delete a model flow chart extension  # noqa: E501

        delete a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_delete_with_http_info(model_flow_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['model_flow_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method model_flow_model_flow_id_extension_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'model_flow_id' is set
        if ('model_flow_id' not in params or
                params['model_flow_id'] is None):
            raise ValueError("Missing the required parameter `model_flow_id` when calling `model_flow_model_flow_id_extension_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'model_flow_id' in params:
            path_params['modelFlowId'] = params['model_flow_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['application']  # noqa: E501

        return self.api_client.call_api(
            '/modelFlow/{modelFlowId}/extension', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def model_flow_model_flow_id_extension_get(self, model_flow_id, **kwargs):  # noqa: E501
        """retrieve a model flow chart extension  # noqa: E501

        retrieve a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_get(model_flow_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :return: list[ModelFlowChartExtensionMeta]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.model_flow_model_flow_id_extension_get_with_http_info(model_flow_id, **kwargs)  # noqa: E501
        else:
            (data) = self.model_flow_model_flow_id_extension_get_with_http_info(model_flow_id, **kwargs)  # noqa: E501
            return data

    def model_flow_model_flow_id_extension_get_with_http_info(self, model_flow_id, **kwargs):  # noqa: E501
        """retrieve a model flow chart extension  # noqa: E501

        retrieve a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_get_with_http_info(model_flow_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :return: list[ModelFlowChartExtensionMeta]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['model_flow_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method model_flow_model_flow_id_extension_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'model_flow_id' is set
        if ('model_flow_id' not in params or
                params['model_flow_id'] is None):
            raise ValueError("Missing the required parameter `model_flow_id` when calling `model_flow_model_flow_id_extension_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'model_flow_id' in params:
            path_params['modelFlowId'] = params['model_flow_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['application']  # noqa: E501

        return self.api_client.call_api(
            '/modelFlow/{modelFlowId}/extension', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[ModelFlowChartExtensionMeta]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def model_flow_model_flow_id_extension_post(self, model_flow_id, model_flow_chart_extension, **kwargs):  # noqa: E501
        """create a model flow chart extension  # noqa: E501

        create a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_post(model_flow_id, model_flow_chart_extension, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :param ModelFlowChartExtensionMeta model_flow_chart_extension: model flow chart extension (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.model_flow_model_flow_id_extension_post_with_http_info(model_flow_id, model_flow_chart_extension, **kwargs)  # noqa: E501
        else:
            (data) = self.model_flow_model_flow_id_extension_post_with_http_info(model_flow_id, model_flow_chart_extension, **kwargs)  # noqa: E501
            return data

    def model_flow_model_flow_id_extension_post_with_http_info(self, model_flow_id, model_flow_chart_extension, **kwargs):  # noqa: E501
        """create a model flow chart extension  # noqa: E501

        create a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_post_with_http_info(model_flow_id, model_flow_chart_extension, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :param ModelFlowChartExtensionMeta model_flow_chart_extension: model flow chart extension (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['model_flow_id', 'model_flow_chart_extension']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method model_flow_model_flow_id_extension_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'model_flow_id' is set
        if ('model_flow_id' not in params or
                params['model_flow_id'] is None):
            raise ValueError("Missing the required parameter `model_flow_id` when calling `model_flow_model_flow_id_extension_post`")  # noqa: E501
        # verify the required parameter 'model_flow_chart_extension' is set
        if ('model_flow_chart_extension' not in params or
                params['model_flow_chart_extension'] is None):
            raise ValueError("Missing the required parameter `model_flow_chart_extension` when calling `model_flow_model_flow_id_extension_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'model_flow_id' in params:
            path_params['modelFlowId'] = params['model_flow_id']  # noqa: E501

        query_params = []
        if 'model_flow_chart_extension' in params:
            query_params.append(('modelFlowChartExtension', params['model_flow_chart_extension']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['application']  # noqa: E501

        return self.api_client.call_api(
            '/modelFlow/{modelFlowId}/extension', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def model_flow_model_flow_id_extension_put(self, model_flow_id, model_flow_chart_extension, **kwargs):  # noqa: E501
        """update a model flow chart extension  # noqa: E501

        update a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_put(model_flow_id, model_flow_chart_extension, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :param ModelFlowChartExtensionMeta model_flow_chart_extension: model flow chart extension (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.model_flow_model_flow_id_extension_put_with_http_info(model_flow_id, model_flow_chart_extension, **kwargs)  # noqa: E501
        else:
            (data) = self.model_flow_model_flow_id_extension_put_with_http_info(model_flow_id, model_flow_chart_extension, **kwargs)  # noqa: E501
            return data

    def model_flow_model_flow_id_extension_put_with_http_info(self, model_flow_id, model_flow_chart_extension, **kwargs):  # noqa: E501
        """update a model flow chart extension  # noqa: E501

        update a model flow chart extension  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.model_flow_model_flow_id_extension_put_with_http_info(model_flow_id, model_flow_chart_extension, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str model_flow_id: model flow chart id (required)
        :param ModelFlowChartExtensionMeta model_flow_chart_extension: model flow chart extension (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['model_flow_id', 'model_flow_chart_extension']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method model_flow_model_flow_id_extension_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'model_flow_id' is set
        if ('model_flow_id' not in params or
                params['model_flow_id'] is None):
            raise ValueError("Missing the required parameter `model_flow_id` when calling `model_flow_model_flow_id_extension_put`")  # noqa: E501
        # verify the required parameter 'model_flow_chart_extension' is set
        if ('model_flow_chart_extension' not in params or
                params['model_flow_chart_extension'] is None):
            raise ValueError("Missing the required parameter `model_flow_chart_extension` when calling `model_flow_model_flow_id_extension_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'model_flow_id' in params:
            path_params['modelFlowId'] = params['model_flow_id']  # noqa: E501

        query_params = []
        if 'model_flow_chart_extension' in params:
            query_params.append(('modelFlowChartExtension', params['model_flow_chart_extension']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['application']  # noqa: E501

        return self.api_client.call_api(
            '/modelFlow/{modelFlowId}/extension', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
